language: java
jdk: openjdk8
sudo: false
install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
deploy:
  - provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: jTelegram/jTelegramBotAPI
      branch: master
  - provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: jTelegram/jTelegramBotAPI
      tags: true
cache:
  directories:
    - "$HOME/.m2"

